### ISSUE TITLE
Accepting PRs?

### ISSUE THREAD

**Issue by chmorgan** [maikmerten/hmp3#3]
I have need for helix in an stm32 project and was hoping pull requests might be accepted here if I make any improvements. If so I’m very glad to see someone keeping this code alive as I’ve had good use of this decoder ported to riscv etc for esp32 usage.

**Comment by maikmerten** [comment]
Hi there,

as long as the patches for stm32 do not interfere with the code working on other platforms (Linux, Windows) and are license-compatible (there might be platform-specific code needed), I can consider pull requests.

Note, however, that this repository contains the Helix MP3 **en**coder, *not* the Helix MP3 **de**coder. Are you certain this is the repository you're looking for?

**Comment by chmorgan** [comment]
@maikmerten oh man... super cringe... didn't realize it was the encoder and not the decoder :-) sorry for the trouble

**Comment by maikmerten** [comment]
Don't worry,  no trouble caused!

For a MP3 decoder, I wonder if something small and self-contained like https://github.com/lieff/minimp3 might work for you. It appears to be neatly organized and comes with a much more open license than anything Helix-based.

**Comment by maikmerten** [comment]
Oh, I see you already discovered https://github.com/lieff/minimp3 :-)

**Comment by chmorgan** [comment]
Minimp3 is nice but for my embedded target without floating point simd it’s taking too long to decode frames, I’m measuring 51ms to decode 1152 samples so 22khz at full tilt.

I’ve forked a version  of helix mp3 decoder that I’ve used before  and plan to use that.
