### ISSUE TITLE
Unsupported PCM file type

### ISSUE THREAD

**Issue by sergeevabc** [maikmerten/hmp3#4]
Dear @maikmerten, recently I have come across a few limitations of Helix MP3 encoder. Both are related to the same error: “UNSUPPORTED PCM FILE TYPE”. Perhaps you could do something about that, since LAME has no such issue.

1. When input's bit depth is not 16 bit, but 24 bit.
2. When input's WAV format is not PcmWaveformat, but [WaveFormatExtensible](https://stackoverflow.com/a/53839949).

**Comment by maikmerten** [comment]
Thanks for reporting this issue. Parts of the code base are somewhat based on the assumption of 16 bit samples and up to two channels, meaning that WAVE_FORMAT_EXTENSIBLE isn't the "natural" input format.

As a workaround I recommend converting files to "normal", old-fashioned .wav (stereo, 16 bit), e.g. using sox or ffmpeg, before submitting them to the MP3 encoder.

I'm leaving this bug report open.

**Comment by sergeevabc** [comment]
And is the signal processed with floating point (as in LAME) or is it an integer as well? You see, when encoding modern music, the signal often goes above 0dB, and I want to understand what happens with those peaks, whether they're irreversibly lost or can be altered later by means of MP3Gain or Replaygain.

**Comment by maikmerten** [comment]
I don't expect hmp3 to handle such cases any different than Lame.

**Comment by sergeevabc** [comment]
Janne Hyvärinen aka Case paid attention to users' concerns about Helix's limitations in sampling rate, bit depth and other audio parameters, and then made the necessary changes to the code. The progress is reflected on [Hydrogenaudio forum][1].

[1]: https://hydrogenaud.io/index.php/topic,123331.msg1040083.html#msg1040083
