### ISSUE TITLE
[Question] Mysterious options

### ISSUE THREAD

**Issue by sergeevabc** [maikmerten/hmp3#5]
Dear @maikmerten,
Helix serves me well, but I'd like to know more about some of its options.
At present their descriptions leave much to be desired.

```
A[algor_select]  0 = track input, 1=MPEG-1, 2=MPEG-2, xxxxx=sample_rate

Q         disable_taper, q0 = base, q1 = fast, q-1 = encoder chooses

TX        tx6, test reserved 6 or 8 seems best (startup_adjustNT1B)
            ** v5.0  TEST 1  as of 8/15/00
            ** v5.0  TEST 2  8/18/00
            ** v5.0  TEST 3  default tx6 (prev = tx8)
            ** v5.0  TEST 4  mods to short fnc_sf, ms corr. hf enable > 80
            ** v5.0  TEST 5  fix odd npart, ix clear
            ** v5.0  TEST 6  add reformatted frames
            ** v5.0  TEST 7  drop V4 amod
            ** v5.1  2005.08.09 (see CVS log for details)

SBT[short_block_threshold]
          short_block_threshold default = 700
```

**Comment by maikmerten** [comment]
These settings are indeed mysterious and seem to select between different attempts to tweak and test things during development. I didn't see any documentation on what changes between these options and what the intended outcomes are. For normal encoding, I thus don't recommend messing with these settings - but anyone feeling a bit adventurous might find it enjoyable to test things out. According to the parameter description "6 or 8 seems best" - whatever that means.

**Comment by sergeevabc** [comment]
Attention to these advanced options was drawn during the recent Helix workshop on Hydrogenaudio forum [here][1] and [there][2]. Perhaps Janne Hivarinen, who edited the code, will finally bring clarity.

[1]: https://hydrogenaud.io/index.php/topic,123331.msg1041407.html#msg1041407
[2]: https://hydrogenaud.io/index.php/topic,123331.msg1041539.html#msg1041539
